# Generated by Django 5.2.5 on 2025-08-20 15:05

import apps.issues.models
import apps.issues.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=apps.issues.models.issue_attachment_path, validators=[apps.issues.utils.validate_file_size, apps.issues.utils.validate_file_type]),
        ),
    ]
