# Generated by Django 5.2.5 on 2025-08-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_attachment_content_type_attachment_file_size_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('issue_created', 'Issue Created'), ('issue_assigned', 'Issue Assigned'), ('issue_updated', 'Issue Updated'), ('issue_resolved', 'Issue Resolved'), ('comment_added', 'Comment Added'), ('feedback_added', 'Feedback Added')], default='issue_updated', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='issues.issue'),
        ),
    ]
